<?php
session_start();

date_default_timezone_set('Asia/Shanghai');

$lockFile = __DIR__ . '/setup.lock';
$errors = [];
$success = false;
$setupBlocked = false;

$availableProviders = ['none'];
$providerDir = __DIR__ . '/track_api';
if (is_dir($providerDir)) {
    $entries = scandir($providerDir);
    if ($entries !== false) {
        foreach ($entries as $entry) {
            if ($entry === '.' || $entry === '..') {
                continue;
            }
            if (substr($entry, -4) !== '.php') {
                continue;
            }
            $availableProviders[] = basename($entry, '.php');
        }
    }
}
$availableProviders = array_values(array_unique($availableProviders));

function h($value) {
    return htmlspecialchars($value ?? '', ENT_QUOTES, 'UTF-8');
}

function setup_csrf_token() {
    if (empty($_SESSION['setup_csrf'])) {
        $_SESSION['setup_csrf'] = bin2hex(random_bytes(16));
    }
    return $_SESSION['setup_csrf'];
}

function setup_require_csrf(&$errors) {
    $token = $_POST['csrf_token'] ?? '';
    if (!hash_equals($_SESSION['setup_csrf'] ?? '', $token)) {
        $errors[] = 'Security token mismatch. Please refresh and try again.';
    }
}

function setup_write_config($configPath, $values) {
    $config = "<?php\n";
    $config .= "# Configuration file for the giveaway system.\n";
    $config .= "# Generated by setup.php.\n";
    $config .= "\n";
    $config .= "# Protect against web entry\n";
    $config .= "if (!defined('GIVEAWAY_SYSTEM')) {\n";
    $config .= "    exit;\n";
    $config .= "}\n\n";
    $config .= "## Site branding\n";
    $config .= '$gsSiteName = ' . var_export($values['site_name'], true) . ";\n";
    $config .= '$gsOwnerName = ' . var_export($values['owner_name'], true) . ";\n";
    $config .= '$gsSiteVersion = ' . var_export($values['site_version'], true) . ";\n";
    $config .= '$gsAdminVersion = ' . var_export($values['admin_version'], true) . ";\n\n";
    $config .= "## Social media settings\n";
    $config .= '$gsSocialPlatform = ' . var_export($values['social_platform'], true) . ";\n";
    $config .= '$gsSocialIdNumericOnly = ' . ($values['social_numeric_only'] ? 'true' : 'false') . ";\n\n";
    $config .= "## Tracking API\n";
    $config .= "# Select the tracking provider file name (without .php) in /track_api\n";
    $config .= '$gsTrackingProvider = ' . var_export($values['tracking_provider'], true) . ";\n";
    $config .= '$gs17TrackApiKey = ' . var_export($values['tracking_17track_key'], true) . ";\n\n";
    $config .= "## Database configuration\n";
    $config .= '$gsDbHost = ' . var_export($values['db_host'], true) . ";\n";
    $config .= '$gsDbName = ' . var_export($values['db_name'], true) . ";\n";
    $config .= '$gsDbUser = ' . var_export($values['db_user'], true) . ";\n";
    $config .= '$gsDbPass = ' . var_export($values['db_pass'], true) . ";\n";
    $config .= '$gsDbCharset = ' . var_export($values['db_charset'], true) . ";\n";

    return file_put_contents($configPath, $config, LOCK_EX);
}

if (is_file($lockFile)) {
    $errors[] = 'Setup has already been completed. Remove setup.lock if you need to re-run the installer.';
    $setupBlocked = true;
}

$defaults = [
    'db_host' => '127.0.0.1',
    'db_name' => 'giveaway_sys',
    'db_user' => '',
    'db_pass' => '',
    'db_charset' => 'utf8mb4',
    'site_name' => 'Giveaway System',
    'owner_name' => 'Site Owner',
    'site_version' => 'V1.0',
    'admin_version' => 'v1.0',
    'social_platform' => 'QQ',
    'social_numeric_only' => true,
    'admin_username' => '',
    'admin_password' => '',
    'admin_password_confirm' => '',
    'admin_social' => '',
    'tracking_provider' => 'none',
    'tracking_17track_key' => '',
];

$values = $defaults;

if ($_SERVER['REQUEST_METHOD'] === 'POST' && empty($errors)) {
    setup_require_csrf($errors);

    foreach ($defaults as $key => $default) {
        if (isset($_POST[$key])) {
            if (is_bool($default)) {
                $values[$key] = $_POST[$key] === '1';
            } else {
                $values[$key] = trim((string)$_POST[$key]);
            }
        }
    }

    if ($values['db_host'] === '' || $values['db_name'] === '' || $values['db_user'] === '') {
        $errors[] = 'Database host, name, and user are required.';
    }
    if (!preg_match('/^[A-Za-z0-9_\-]+$/', $values['db_name'])) {
        $errors[] = 'Database name may only contain letters, numbers, underscores, and dashes.';
    }
    if ($values['site_name'] === '' || $values['owner_name'] === '') {
        $errors[] = 'Site name and owner name are required.';
    }
    if ($values['social_platform'] === '') {
        $errors[] = 'Social platform name is required.';
    }
    if ($values['admin_username'] === '' || $values['admin_password'] === '' || $values['admin_password_confirm'] === '') {
        $errors[] = 'Admin username and password are required.';
    }
    if ($values['admin_password'] !== $values['admin_password_confirm']) {
        $errors[] = 'Admin passwords do not match.';
    }
    if (strlen($values['admin_password']) < 8) {
        $errors[] = 'Admin password must be at least 8 characters.';
    }
    if ($values['admin_social'] === '') {
        $errors[] = 'Admin social media ID is required.';
    }
    if ($values['social_numeric_only'] && !preg_match('/^[0-9]+$/', $values['admin_social'])) {
        $errors[] = 'Admin social media ID must be numeric.';
    }

    if (!in_array($values['tracking_provider'], $availableProviders, true)) {
        $errors[] = 'Selected tracking provider is invalid.';
    }

    if (empty($errors)) {
        $dbCharset = $values['db_charset'] ?: 'utf8mb4';
        $createCharset = preg_replace('/[^a-z0-9_]/i', '', $dbCharset);
        $dsnBase = 'mysql:host=' . $values['db_host'] . ';charset=' . $createCharset;

        try {
            $pdo = new PDO($dsnBase, $values['db_user'], $values['db_pass'], [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);

            $collation = $createCharset === 'utf8mb4' ? 'utf8mb4_unicode_ci' : $createCharset . '_general_ci';
            $pdo->exec(
                sprintf(
                    "CREATE DATABASE IF NOT EXISTS `%s` DEFAULT CHARACTER SET %s COLLATE %s",
                    str_replace('`', '``', $values['db_name']),
                    $createCharset,
                    $collation
                )
            );

            $dsnDb = 'mysql:host=' . $values['db_host'] . ';dbname=' . $values['db_name'] . ';charset=' . $createCharset;
            $pdo = new PDO($dsnDb, $values['db_user'], $values['db_pass'], [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ]);

            $schemaSql = file_get_contents(__DIR__ . '/docs/init-db.sql');
            if ($schemaSql === false) {
                throw new RuntimeException('Could not read schema file.');
            }
            $schemaSql = preg_replace('/--.*$/m', '', $schemaSql);
            $schemaSql = preg_replace('/CREATE DATABASE.*?;\s*/is', '', $schemaSql, 1);
            $schemaSql = preg_replace('/USE\s+`?[^`\s;]+`?\s*;\s*/i', '', $schemaSql, 1);
            $statements = array_filter(array_map('trim', explode(';', $schemaSql)));
            foreach ($statements as $statement) {
                $pdo->exec($statement);
            }

            $adminHash = password_hash($values['admin_password'], PASSWORD_DEFAULT);
            $stmt = $pdo->prepare(
                "INSERT INTO users (uid, pwdhash, qq, user_group, verified, disabled) VALUES (?, ?, ?, 'owner', 1, 0)"
            );
            $stmt->execute([
                $values['admin_username'],
                $adminHash,
                $values['admin_social'],
            ]);

            if (!is_writable(__DIR__ . '/config.php')) {
                throw new RuntimeException('config.php is not writable. Please adjust file permissions and try again.');
            }

            $configValues = [
                'site_name' => $values['site_name'],
                'owner_name' => $values['owner_name'],
                'site_version' => $values['site_version'],
                'admin_version' => $values['admin_version'],
                'social_platform' => $values['social_platform'],
                'social_numeric_only' => $values['social_numeric_only'],
                'tracking_provider' => $values['tracking_provider'],
                'tracking_17track_key' => $values['tracking_provider'] === '17track' ? $values['tracking_17track_key'] : '',
                'db_host' => $values['db_host'],
                'db_name' => $values['db_name'],
                'db_user' => $values['db_user'],
                'db_pass' => $values['db_pass'],
                'db_charset' => $values['db_charset'],
            ];

            if (!setup_write_config(__DIR__ . '/config.php', $configValues)) {
                throw new RuntimeException('Unable to write config.php.');
            }

            file_put_contents($lockFile, 'Setup completed at ' . date('c'));
            $success = true;
        } catch (Throwable $e) {
            $errors[] = 'Setup failed: ' . $e->getMessage();
        }
    }
}

$csrfToken = setup_csrf_token();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Setup Wizard - Giveaway System</title>
    <style>
        body { font-family: Arial, sans-serif; background: #f4f6f8; margin: 0; padding: 30px; }
        .container { max-width: 720px; margin: 0 auto; background: #fff; padding: 24px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { margin-top: 0; }
        .section { margin-top: 24px; }
        label { display: block; margin: 10px 0 6px; font-weight: 600; }
        input[type="text"], input[type="password"], select { width: 100%; padding: 8px 10px; border: 1px solid #ccc; border-radius: 4px; }
        .row { display: flex; gap: 16px; }
        .row > div { flex: 1; }
        .note { background: #f0f4ff; padding: 12px; border-radius: 6px; font-size: 0.9em; }
        .error { background: #ffe5e5; color: #b40000; padding: 12px; border-radius: 6px; }
        .success { background: #e7f8ed; color: #1a6b2b; padding: 12px; border-radius: 6px; }
        .actions { margin-top: 20px; }
        .actions button { padding: 10px 18px; border: none; background: #2d6cdf; color: #fff; border-radius: 4px; cursor: pointer; }
        .actions button:disabled { background: #aab7d6; }
    </style>
</head>
<body>
<div class="container">
    <h1>Giveaway System Setup</h1>

    <?php if (!empty($errors)): ?>
        <div class="error">
            <strong>Setup blocked:</strong>
            <ul>
                <?php foreach ($errors as $error): ?>
                    <li><?php echo h($error); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <?php if ($success): ?>
        <div class="success">
            <strong>Setup completed!</strong>
            <p>Your configuration file has been written, the database schema was created, and the owner account is ready.</p>
            <p><strong>Security:</strong> delete <code>setup.php</code> or keep <code>setup.lock</code> in place to prevent re-running the installer.</p>
        </div>
    <?php elseif ($setupBlocked): ?>
        <div class="note">
            <strong>Setup locked.</strong>
            <p>Remove <code>setup.lock</code> only if you need to re-run the installer on a fresh database.</p>
        </div>
    <?php else: ?>
        <p class="note">
            This installer will create the database schema and an owner account. Do not run it on a production system with existing data.
        </p>

        <form method="post">
            <input type="hidden" name="csrf_token" value="<?php echo h($csrfToken); ?>">

            <div class="section">
                <h2>Database</h2>
                <div class="row">
                    <div>
                        <label for="db_host">Database host</label>
                        <input id="db_host" type="text" name="db_host" value="<?php echo h($values['db_host']); ?>" required>
                    </div>
                    <div>
                        <label for="db_name">Database name</label>
                        <input id="db_name" type="text" name="db_name" value="<?php echo h($values['db_name']); ?>" required>
                    </div>
                </div>
                <div class="row">
                    <div>
                        <label for="db_user">Database user</label>
                        <input id="db_user" type="text" name="db_user" value="<?php echo h($values['db_user']); ?>" required>
                    </div>
                    <div>
                        <label for="db_pass">Database password</label>
                        <input id="db_pass" type="password" name="db_pass" value="<?php echo h($values['db_pass']); ?>">
                    </div>
                </div>
                <label for="db_charset">Database charset</label>
                <input id="db_charset" type="text" name="db_charset" value="<?php echo h($values['db_charset']); ?>">
            </div>

            <div class="section">
                <h2>Site Settings</h2>
                <label for="site_name">Site name</label>
                <input id="site_name" type="text" name="site_name" value="<?php echo h($values['site_name']); ?>" required>

                <label for="owner_name">Owner name</label>
                <input id="owner_name" type="text" name="owner_name" value="<?php echo h($values['owner_name']); ?>" required>

                <div class="row">
                    <div>
                        <label for="site_version">Site version label</label>
                        <input id="site_version" type="text" name="site_version" value="<?php echo h($values['site_version']); ?>">
                    </div>
                    <div>
                        <label for="admin_version">Admin version label</label>
                        <input id="admin_version" type="text" name="admin_version" value="<?php echo h($values['admin_version']); ?>">
                    </div>
                </div>

                <div class="row">
                    <div>
                        <label for="social_platform">Social platform name</label>
                        <input id="social_platform" type="text" name="social_platform" value="<?php echo h($values['social_platform']); ?>" required>
                    </div>
                    <div>
                        <label for="social_numeric_only">Social ID numeric only</label>
                        <select id="social_numeric_only" name="social_numeric_only">
                            <option value="1" <?php echo $values['social_numeric_only'] ? 'selected' : ''; ?>>Yes</option>
                            <option value="0" <?php echo !$values['social_numeric_only'] ? 'selected' : ''; ?>>No</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="section">
                <h2>Owner Account</h2>
                <label for="admin_username">Admin username</label>
                <input id="admin_username" type="text" name="admin_username" value="<?php echo h($values['admin_username']); ?>" required>

                <div class="row">
                    <div>
                        <label for="admin_password">Admin password</label>
                        <input id="admin_password" type="password" name="admin_password" required>
                    </div>
                    <div>
                        <label for="admin_password_confirm">Confirm password</label>
                        <input id="admin_password_confirm" type="password" name="admin_password_confirm" required>
                    </div>
                </div>

                <label for="admin_social">Admin social media ID</label>
                <input id="admin_social" type="text" name="admin_social" value="<?php echo h($values['admin_social']); ?>" required>
            </div>

            <div class="section">
                <h2>Tracking API (Optional)</h2>
                <label for="tracking_provider">Provider</label>
                <select id="tracking_provider" name="tracking_provider">
                    <?php foreach ($availableProviders as $provider): ?>
                        <option value="<?php echo h($provider); ?>" <?php echo $values['tracking_provider'] === $provider ? 'selected' : ''; ?>>
                            <?php echo $provider === 'none' ? 'None (disabled)' : h($provider); ?>
                        </option>
                    <?php endforeach; ?>
                </select>

                <label for="tracking_17track_key">17Track API key (if using 17track)</label>
                <input id="tracking_17track_key" type="text" name="tracking_17track_key" value="<?php echo h($values['tracking_17track_key']); ?>">
            </div>

            <div class="actions">
                <button type="submit">Run setup</button>
            </div>
        </form>
    <?php endif; ?>
</div>
</body>
</html>
